import type { Item } from "./src/models/Item";

export const clothing: Item[] = [
    {
        id: 1,
        name: "Classic White T-Shirt",
        description: "Soft cotton t-shirt with a regular fit, perfect for everyday wear.",
        gender: "Unisex",
        size: "M",
        color: "white",
        category: "t-shirts",
        brand: "FitWear",
        material: "100% cotton",
        createdAt: new Date("2025-09-15T12:00:00Z"),
        price: 29.99,
        stock: 45,
        imageUrl: "https://picsum.photos/id/1/200/300",
    },
    {
        id: 2,
        name: "Denim Jacket",
        description: "Stylish blue denim jacket with button closure and chest pockets.",
        gender: "Male",
        size: "L",
        color: "blue",
        category: "jackets",
        brand: "UrbanEdge",
        material: "Denim",
        createdAt: new Date("2025-08-20T10:30:00Z"),
        price: 89.5,
        stock: 22,
        imageUrl: "https://picsum.photos/id/2/200/300",
    },
    {
        id: 3,
        name: "Black Leather Boots",
        description: "Durable leather boots with rubber soles and side zipper.",
        gender: "Female",
        size: "M",
        color: "black",
        category: "footwear",
        brand: "TrailStep",
        material: "Leather",
        createdAt: new Date("2025-10-01T09:45:00Z"),
        price: 129.99,
        stock: 15,
        imageUrl: "https://picsum.photos/id/3/200/300",
    },
    {
        id: 4,
        name: "Gray Sweatpants",
        description: "Comfortable fleece sweatpants with elastic waistband and drawstring.",
        gender: "Unisex",
        size: "L",
        color: "gray",
        category: "pants",
        brand: "CozyLife",
        material: "Cotton Blend",
        createdAt: new Date("2025-09-10T08:15:00Z"),
        price: 49.99,
        stock: 60,
        imageUrl: "https://picsum.photos/id/4/200/300",
    },
    {
        id: 5,
        name: "Floral Summer Dress",
        description: "Lightweight floral dress ideal for summer outings.",
        gender: "Female",
        size: "S",
        color: "pink",
        category: "dresses",
        brand: "BloomWear",
        material: "Polyester",
        createdAt: new Date("2025-07-30T14:25:00Z"),
        price: 59.0,
        stock: 30,
        imageUrl: "https://picsum.photos/id/5/200/300",
    },
    {
        id: 6,
        name: "Black Hoodie",
        description: "Cozy black hoodie with kangaroo pocket and adjustable hood.",
        gender: "Male",
        size: "XL",
        color: "black",
        category: "hoodies",
        brand: "StreetLine",
        material: "Fleece",
        createdAt: new Date("2025-10-10T17:00:00Z"),
        price: 69.99,
        stock: 40,
        imageUrl: "https://picsum.photos/id/6/200/300",
    },
    {
        id: 7,
        name: "Running Shorts",
        description: "Lightweight athletic shorts with breathable mesh lining.",
        gender: "Male",
        size: "M",
        color: "navy",
        category: "shorts",
        brand: "ActivePro",
        material: "Polyester",
        createdAt: new Date("2025-09-25T11:10:00Z"),
        price: 34.5,
        stock: 55,
        imageUrl: "https://picsum.photos/id/7/200/300",
    },
    {
        id: 8,
        name: "Wool Scarf",
        description: "Soft and warm wool scarf, perfect for cold days.",
        gender: "Unisex",
        size: "One Size",
        color: "red",
        category: "accessories",
        brand: "WinterTouch",
        material: "Wool",
        createdAt: new Date("2025-10-05T13:50:00Z"),
        price: 24.99,
        stock: 75,
        imageUrl: "https://picsum.photos/id/8/200/300",
    },
];



export const categories = [
    { "id": 1, "name": "T-shirts", "gender": "unisex" },
    { "id": 2, "name": "Jackets", "gender": "unisex" },
    { "id": 3, "name": "Pants", "gender": "unisex" },
    { "id": 4, "name": "Dresses", "gender": "female" },
    { "id": 5, "name": "Footwear", "gender": "unisex" },
    { "id": 6, "name": "Hoodies", "gender": "unisex" },
    { "id": 7, "name": "Shorts", "gender": "unisex" },
    { "id": 8, "name": "Accessories", "gender": "unisex" }
]
export const brands = [
    { "id": 1, "name": "FitWear" },
    { "id": 2, "name": "UrbanEdge" },
    { "id": 3, "name": "TrailStep" },
    { "id": 4, "name": "CozyLife" },
    { "id": 5, "name": "BloomWear" },
    { "id": 6, "name": "StreetLine" },
    { "id": 7, "name": "ActivePro" },
    { "id": 8, "name": "WinterTouch" }
];
export const colors = [
    "white",
    "black",
    "blue",
    "gray",
    "pink",
    "navy",
    "red"
];
export const sizes = [
    "XS",
    "S",
    "M",
    "L",
    "XL",
    "XXL",
    "One Size",
    "38"
];